menu:
  Home: /
  Archives: /archives

# duoshuo comment
duoshuo: false
duoshuo_name: cheris-github
duoshuo_embed: //assets-github.cheris.com.cn/js/duoshuo

# disqus comment
disqus: false
disqus_shortname: cheris-github

# google analytics
googleTrackId: UA-37234333-2
qqTaId: 58158453


# feed 
github: cherislive
username : cheris
userpost : Front-End Engineer

