menu:
  Home: /
  Archives: /archives

# duoshuo comment
duoshuo: true
duoshuo_name: cherislive

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: 


# feed 
rss: /feed.xml
username : cheris
userpost : Front-End Engineer

