menu:
  Home: /
  Archives: /archives

# duoshuo comment
duoshuo: true
duoshuo_name: cherislive

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: UA-37234333-2
qqTaId: 58158453


# feed 
github: cherislive
username : cheris
userpost : Front-End Engineer

